language: android
sudo: false
android:
  components:
  - build-tools-24.0.0
  - android-24
  - extra-android-m2repository
  - extra-android-support
script:
- ./gradlew assembleRelease
deploy:
  provider: releases
  api_key:
    secure: QoYgcNpXMEcxLsRl4YmWCbEc8ZI40KXviFHwcgmMPQlEIpvqivcCyTkFHh9FxlmJgwtuVpBPTniIhkpuUesIxD2AQmFLzY1vqGQDtFylRmv2b0IwmRp4m7J2FAmc5kEo8kK6QBUvQNBc+9+nL7aovvHZW9wwestpFBAqlwvsS3SLFNGPiCcVh2+9ArWjt1IYOyf70mXK+XMSk/BrsQNeVb0niKKZzwttlAJrZQsBBpHCfEjwQ58Uye9Zd8zWgGapzSyCQdX/6XdEyu7OCUCE4+yESPUV6CIwN9bLEXwsG4KDduVFvCwFC/ec4rSFH/9D1xwgcxR1sxhL9oWrT3KMbExrCHuqppmRgwMbxrgNHzG4CVT21KZ2I0arQYqfcZNLOXdbryEFq26b4QnWz1M3v5EOJQVTorjhrI3/ZyddwVbGrRdfk/1dJl++H5GY/l2P+9bGnvvH/qcIC1qlsrdAyt3uLO+e6WgACQ3bJgeHJGScFF4X3YehVb3NR0jdkNxMMpuUacnRBQArjBTHA3DAgUz/kwoaV7rNsThcu+OiesYXqPA99R6HdoJ+rQIX0313dzEas8mWFiryHJrMFmVadwYJ0uBgPsHsVmrCBYvrj18F0BmMLG0A8dQIHhB0imWdED0Jcglg1RfewwCxtOoZDukh+zwXnQeRGFHMgoKUbRg=
  file: update 17:08
  on:
    repo: amyliu1062/TrialCIDemo
