language: android
sudo: false
android:
  components:
  - build-tools-24.0.0
  - android-24
  - extra-android-m2repository
  - extra-android-support
script:
- ./gradlew assembleRelease
deploy:
  provider: releases
  api_key:
    secure: c8Q/Y0zvDllBhEvubRVIjPwzf40ohvUSpr4UVSOXyaqUr9hcydFtAeBf0SyVnOBzCXd9qrT745HMtPDtO/htN1IIMbPZtbi037WJkRihz8PvSeGFjGXwArGnJ80qD4iuEWrHaxQ8nVj0HaoVdW98W9K1qMb4qIG1+kmiT4AMa4EqDxZAWVf2HaOuAW4akNUfg6DTBXtaWxkdj9DFH8aZR7puXNcOVP+jT2bQgk+1SDpy/NZxFzRSLOhT4oH4qPWkr+9XqYbN4xiHhftOOM1OWN4he7u/6+wU97E9C0zJK6NvuUf0HQ205pN2TdX+qYYFU+TU6m4V9pz6/ca2QPCej5Xf8WEGBNhqUe93GqwGmMU4NAR5KxJROmqMSdrGTQ+88Yk8STWIYggRrGAMBHQe0wp2i+ZWnvWfzR84Awn0rjmyVSmBTxAVCVgmOo1ceQP4RAHTMHFCbSLQwEkClEfS0np+ohw7LsvWEUPp4b4QxNtsT6MZ11pdeui9tdHupMyfgKrQMjmzq1DsNphi79mT4R4aAtRmmnW5CpNHWIuuYdTagX0Ggyoiot7u54Zyqs2vYiaU3CcMxgenuwSSWHHaPoq9epr/iR3hvjHk992T4X9WgpSAm8YZ9XSghNZc3Ajk/g86PT5WUEyhqcZd51iXPQ825rN40iyUIIdtgn1QKSc=
  file: update 1
  on:
    tags: true
    repo: amyliu1062/TrialCIDemo
