language: android
sudo: false
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-android-support
script:
- ./gradlew assembleRelease
deploy:
  provider: releases
  api_key:
    secure: Eh85WWErG1E5DHfiVH75Kdib7sEPtIZ4//v5gXMPmZkrpo2uaNqr03+TbMlpvyvRJXjSl2UESurbEt5CYvSve4C6gcE8PPHy6ique0x2pUDMr+jojwrExDFvpGp91Y4rPxKwbzQ9w1A/4rDglK+Hns+rc+IjNSpKEV2w20zjF6/jF378T7ChTEepYp84tToAn+OLUKesIC6ETXNrvgQt7OPPjN8txrYq09Z9l2YtWoB7ZolqdRmE+BDxyJHCv058DO4XrVPTtTEFIr96R1iIlN0oCEIt+e+QUPjzgiOvMPxFWdXQs+R6dN3F91cffwAFWBcAFucKioAUgp5qTV7l9VOpBWFDh2q+gVQ/SLLxp/xpvq4q8rTFXP6/OvwtnZRuv0LngYy4rfAUZFieocal136WpPZCXo6zo4kOAB3R6ZCma5+M7pdIY2ZD7yMRw1bwBOKLF9hhfFUKREDg1ytu69tegbdSIDYNXfpNBeXw9frkIBtUaGwacXlJZiO4i6xvDjpLdGomET548z0hD9iuGUb/U84UJCPg6kqFK8rOSap13WJlGeTy8ZLKFSuPCwGbAcntt0U6sWQY10nERvtImNKiWIqD7Exi/wWJXsPLW27b1fv4NozX0vReYNXOpMw71Moz3pNwLTOrBgeP/RS0FIqcPghnY416ZKF7JQnvFDs=
  file: update 17:03
  on:
    tags: true
    repo: amyliu1062/TrialCIDemo
