language: android
sudo: false
android:
  components:
  - build-tools-24.0.0
  - android-24
  - extra-android-m2repository
  - extra-android-support
script:
- ./gradlew assembleRelease
deploy:
  provider: releases
  api_key:
    secure: DnyCFphou/S33aL3/Aw8Qlq5rO+W/jtzY7T/3yXD7xHABaRUHxMoF01l9gcSkHS5DmusELxTrUSQs6W8fPt8glFBNvQemTf2prfciJXJJmuh599AFQPS6lvWaf/klIpYfSCGKT9toQqMyFXTRA15x+cwcEW5t6gxvwJHRGls/Cqz8TZ7G9Je6TKmm4mIXwgIpVviqLyFbohJSBoN2BE+p99ugpg7OvpwTK1OKFuZ6MCAzDUKxlJfcAKCXlHaQFPV+1+lsNrqq5reHaOmcdoVIIRUJwEautPuqydo+jWmwvRf1WJwbVEjUg4qWDC1u+FeK4hO3RzVrE0ej49MtxEDBGOGZMdutxiOKlcAAki4JI5zYLwDNxGx4vVRFI6Dfo+YfZDnAt/RTVPlSFaXBqVCzrTEnCOi4A9qcOD/yxyDHw1FzuLoHU3u8dUeyiW/wOMv+Ffb0Lv7Hhj595jDV0zhxPxPS3gQWiX7UFQnqiU6IGfvcrWQKnTfbex3qI3gvvf2mz+ClbS/594Q5IZRJuZcH3aBXfnmrr0kodgh0nZZCjMynrci5iGdN40JvjJkp7PylQE6A3QQcCFql9ym5yWYNk/1snnDl+ExgZOQWBV6NRGEQuW7mnppx8cLmbt34lXxTxoH0gsbKPbtefaDzFWpKqyy/AYvnITa/bDyCgEAGdo=
  file: '58'
  on:
    repo: amyliu1062/TrialCIDemo
