language: android
sudo: false
android:
  components:
  - build-tools-24.0.0
  - android-24
  - extra-android-m2repository
  - extra-android-support
script:
- ./gradlew assembleRelease
deploy:
  provider: releases
  api_key:
    secure: YMLpOv0s91WHONI8CDyVmhyJvX/nL3EodT8+sm07H3c563Ru+jGbxbUdlQ3tzSWiu07ANgEGIBbWbr+SBgcaD4zW8f0NZz8TWqzxy11iX4TMP9EIcOnKldWUP76u+/MP0aziaGPmmpkMEcrcyiBlSSVBcYyXsSegWH/z7JDWDfVmu1j4JdtcSjKyyoIf2M1RhXcWC2gK+TR9ZSHltFtuIUF5o3yF9j3zZIlDUNabAUKFcwVRNzwZFDgFqyHRgse3kFHtba/iS9F+9u5UlRyFW+9UDDdGVj1idT0QzJnO9P9nOAK/s4o1n8YLr2zhpRzhUCYqyjlk68zelJ8vV/6eWZwxw9wXIaS1y/xosRa4rCOuVWqNVrG1PUo7/wU7IMetFTJt6oSl/8TnNmreXxTelJG6MdFXe4I5NdJzyrdNy9MVNwo6h4ov9Js52PNuQBF+oe86CkXM01bnUR1t6vnC5yn9HJJL2igjMfYsivMiVF/twyJRJOmanwJaB9uW768k3/H62mUemkgZ9lM3UZda53xdPhoRHoecBlPNgw3E99UDiG9Prhi1SxBszQByfHQKrCfEQzO/iX+ksLY2CRlNnlobzNFKrdkmWccvnAFX/HEmlUIoLmVasykfnfqhrDVPFkSPrMiwVDzvID2iqBRSJIBleo/yycUK/MPrdbAxOWw=
  file: update 17:18
  on:
    tags: true
    repo: amyliu1062/TrialCIDemo
